// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "WWDC2024",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "WWDC2024",
            targets: ["AppModule"],
            bundleIdentifier: "com.dhia.wwdc.WWDC2024",
            teamIdentifier: "L59WRJUK24",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "This app requires access to the camera to allow you to take and upload photos of your pets.This app requires access to the camera to allow you to take and upload photos of your pets."),
                .photoLibrary(purposeString: "This app requires access to your photo library to allow you to choose and upload photos of your pets."),
                .fileAccess(.pictureFolder, mode: .readOnly)
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)